version: "3.8"
services:
  webapp:
    container_name: "webapp"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - NUXT_API_PROXY=http://template-webapp:3000
    command: node .output/server/index.mjs
    networks:
      - main

volumes:
  database:

networks:
  main:
    name: main
